### ISSUE TITLE
Could you add .env file for configuration?

### ISSUE THREAD

**Issue by meta-crawler** [moutafatin1/fullstack-todoapp#1]
After running `npm run dev`, I got this error.
![image](https://user-images.githubusercontent.com/114304642/228713323-2b65f221-c68b-4aa3-b3a9-43b661bb34f6.png)

I think this repository doesn't include `.env` file.

So, could you let me know how to configure `.env` file?

Thank you.

**Comment by moutafatin1** [comment]
Yo,
You only need one variable in the env.
You can create a new .nev file and add `DATABASE_URL=file:./dev.db`.
and run `npx prisma migrate dev`, you will be able to run ` npm run dev` after that.
